name: Check and Test Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install linter
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run linter
      run: |
        black --check .
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pytest, coverage and requirements
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install -r requirements.txt
    - name: Run tests
      run: |
        coverage run -m pytest
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: .coverage
        retention-days: 1
  coverage_report:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: coverage
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install coverage
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Report coverage
      run: |
        coverage report
    - name: Export coverage report to xml
      run: |
        coverage xml
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
        retention-days: 14
