name: Check and Test Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install linter
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run linter
      run: |
        black --check .
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pytest, coverage and requirements
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install -r requirements.txt
    - name: Run tests
      run: |
        coverage run -m pytest
